site_name: Roxxel
site_description: A zero-RAM, JAX-centric dataloading, streaming, and asynchronous checkpointing & logging toolkit.
site_author: anon160
repo_name: anon160/Roxxel
repo_url: https://github.com/anon160/Roxxel

theme:
  name: material
  palette:
    - media: '(prefers-color-scheme)'
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow

nav:
  - Welcome: index.md
  - Dataloader & Streaming: dataloader_and_streaming.md
  - Asynchronous Checkpointing: checkpointing.md
  - Asynchronous Logging: logging.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
