site_name: Roxxel
site_description: A zero-RAM, JAX-centric dataloading, streaming, and asynchronous checkpointing & logging toolkit.
site_author: anon160
repo_name: anon160/Roxxel
repo_url: https://github.com/anon160/Roxxel

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: grey
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tracking
    - search.suggest
    - toc.follow

nav:
  - Welcome: index.md
  - Why Roxxel: why_roxxel.md
  - Tutorial: tutorial.md
  - Dataloader & Streaming: dataloader_and_streaming.md
  - Curriculum Blending: curriculum.md
  - Training & Orchestration: trainer.md
  - Checkpointing: checkpointing.md
  - Logging: logging.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false

extra_css:
  - stylesheets/extra.css
